sudo: required
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.8.4
        - DOCKER_REPO=smeat/alpine
    matrix:
        - ARCH=x86      VERSION=v3.4    QEMU_ARCH=i386 DOCKER_ARCH=386
        - ARCH=x86_64   VERSION=v3.4    QEMU_ARCH=x86_64 DOCKER_ARCH=amd64
        - ARCH=armhf    VERSION=v3.4    QEMU_ARCH=arm DOCKER_ARCH=arm

        - ARCH=x86      VERSION=v3.5    QEMU_ARCH=i386 DOCKER_ARCH=386
        - ARCH=x86_64   VERSION=v3.5    QEMU_ARCH=x86_64 DOCKER_ARCH=amd64
        - ARCH=armhf    VERSION=v3.5    QEMU_ARCH=arm DOCKER_ARCH=arm
        - ARCH=aarch64  VERSION=v3.5    QEMU_ARCH=aarch64 DOCKER_ARCH=arm64

        - ARCH=x86      VERSION=latest-stable    QEMU_ARCH=i386 DOCKER_ARCH=386
        - ARCH=x86_64   VERSION=latest-stable    QEMU_ARCH=x86_64 DOCKER_ARCH=amd64
        - ARCH=armhf    VERSION=latest-stable    QEMU_ARCH=arm DOCKER_ARCH=arm
        - ARCH=aarch64  VERSION=latest-stable    QEMU_ARCH=aarch64 DOCKER_ARCH=arm64

        - ARCH=x86      VERSION=edge    QEMU_ARCH=i386 DOCKER_ARCH=386
        - ARCH=x86_64   VERSION=edge    QEMU_ARCH=x86_64 DOCKER_ARCH=amd64
        - ARCH=armhf    VERSION=edge    QEMU_ARCH=arm DOCKER_ARCH=arm
        - ARCH=aarch64  VERSION=edge    QEMU_ARCH=aarch64 DOCKER_ARCH=arm64
before_script:
    - sudo apt-get -y install qemu-user-static
script:
    - sudo ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then sh ./docker_upload.sh $DOCKER_USERNAME $DOCKER_PASSWORD $DOCKER_REPO $ARCH $VERSION $DOCKER_ARCH; fi
